wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.23.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.14
    start_time: 1666782791.204299
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.9.14
      5: 0.13.4
      6: 4.23.1
      8:
      - 5
