clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 23

    # The number of clients selected in each round
    per_round: 23

    # Should the clients compute test accuracy locally?
    do_test: 23

    random_seed: 1

    # FedProx hyperparameters
    proximal_term_penalty_constant: 1

    # FedProx parameters for experiment
    straggler_simulation: true
    straggler_percentage: 50

server:
    address: 127.0.0.1
    port: 8000
    synchronous: true
    do_test: false

    checkpoint_path: models/fedprox/embryos
    model_path: models/fedprox/embryos

data:
    # The training and testing dataset
    datasource: Embryos

    # Number of samples in each partition
    #partition_size: 600

    # IID or non-IID?
    sampler: all_inclusive

    # The concentration parameter for the Dirichlet distribution
    #concentration: 5

    # The random seed for sampling data
    #random_seed: 1

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 20

    # The maximum number of clients running concurrently
    max_concurrency: 10

    # The target accuracy
    target_accuracy: 0.94

    # Number of epochs for local training in each communication round
    epochs: 2
    batch_size: 32
    optimizer: RMSProp

    # The machine learning model
    model_name: lowgpu

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    optimizer:
        lr: 0.0001
        momentum: 0.0 # learning rate is fixed as in Appendix C.2
        weight_decay: 0.000001
